import 'package:flutter/cupertino.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';

class DatabaseHelper {
  static Database? _database;
  static const String dbName = 'students.db';
  static const String tableName = 'students';

  // Singleton instance of Database
  static Future<Database> get database async {
    if (_database != null) return _database!;

    // If _database is null, instantiate it
    _database = await _initDatabase();
    return _database!;
  }

  // Initialize database
  static Future<Database> _initDatabase() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    String path = join(documentsDirectory.path, dbName);

    return await openDatabase(path, version: 1, onCreate: _createTable);
  }

  // Create table
  static Future<void> _createTable(Database db, int version) async {
    await db.execute('''
      CREATE TABLE $tableName (
        id INTEGER PRIMARY KEY,
        student_name TEXT,
        program TEXT,
        branch TEXT,
        year INTEGER,
        semester INTEGER,
        section TEXT,
        Applied_Physics INTEGER,
        English INTEGER,
        Calculus INTEGER,
        Chemistry INTEGER,
        BEE INTEGER,
        Engineering_Drawing INTEGER,
        COA INTEGER,
        Com_English INTEGER,
        CSE_Basics INTEGER,
        OOPs INTEGER,
        Signal_And_Systems INTEGER,
        Digital_Principals INTEGER,
        Probability INTEGER,
        DSA INTEGER,
        OS INTEGER,
        DBMS INTEGER,
        MPI INTEGER,
        EF INTEGER,
        CN INTEGER,
        SE INTEGER,
        AI INTEGER,
        Computing_Concepts INTEGER,
        Network_Security INTEGER,
        DWDM INTEGER,
        MSC INTEGER,
        Cyber_Security INTEGER,
        Data_And_Security INTEGER,
        IS INTEGER,
        EEM INTEGER,
        IP INTEGER,
        MOM INTEGER,
        Ethics_Of_IT INTEGER,
        SLT INTEGER,
        HCI INTEGER,
        Project INTEGER,
        ET INTEGER,
        CS INTEGER,
        Maths_3 INTEGER,
        ED INTEGER,
        SA INTEGER,
        DE INTEGER,
        Maths_4 INTEGER,
        MD INTEGER,
        IA INTEGER,
        SI INTEGER,
        HP INTEGER,
        AC INTEGER,
        TE INTEGER,
        DSP INTEGER,
        VLST_Technology INTEGER,
        PE INTEGER,
        FML INTEGER,
        IM INTEGER,
        OE INTEGER,
        Dissertation INTEGER,
        CF INTEGER,
        POM INTEGER,
        PPA INTEGER,
        Maths-1 INTEGER,
        BC INTEGER,
        C_Programming INTEGER,
        OB INTEGER,
        DE_and_COA INTEGER,
        Maths-2 INTEGER,
        FAM INTEGER,
        SE_2 INTEGER,
        JAVA INTEGER,
        Python INTEGER,
        E-Commerce INTEGER,
        OST INTEGER,
        WBA INTEGER,
        WD INTEGER,
        LOS INTEGER,
        DS INTEGER,
        AD INTEGER
      )
    ''');
  }


  // Insert a student record
  static Future<int> insertStudent(Map<String, dynamic> student) async {
    Database db = await database;
    return await db.insert(tableName, student);
  }


  // Retrieve all students
  static Future<List<Map<String, dynamic>>> getAllStudents() async {
    Database db = await database;
    return await db.query(tableName);
  }

  void main() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Initialize database
    await DatabaseHelper.database;

    // Sample data: List of students
    List<Map<String, dynamic>> students = [
      {
        'student_name': 'John Doe',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section':'A',
        'Applied_Physics':1,
        'English':1 ,
        'Calculus':1,
        'Chemistry':1,
        "BEE":1,
      },
      {
        'student_name': 'John Doe',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Alice Smith',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Emily Johnson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Michael Brown',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Sophia Davis',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'David Wilson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Olivia Taylor',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Daniel Martinez',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Ella Anderson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Liam Clark',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },{
        'student_name': 'John Doe',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Alice Smith',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Emily Johnson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Michael Brown',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Sophia Davis',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'David Wilson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Olivia Taylor',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Daniel Martinez',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Ella Anderson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Liam Clark',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Ava Baker',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Mason Green',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Luna Rivera',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Jackson Hall',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Scarlett Moore',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'John Doe',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Alice Smith',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Emily Johnson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Michael Brown',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Sophia Davis',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'David Wilson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Olivia Taylor',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Daniel Martinez',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Ella Anderson',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Liam Clark',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Ava Baker',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Mason Green',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Luna Rivera',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Jackson Hall',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Scarlett Moore',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },
      {
        'student_name': 'Nathan Turner',
        'program': 'B.Tech',
        'branch': 'CSE',
        'year': 1,
        'semester': 1,
        'section': 'A',
        'Applied_Physics': 1,
        'English': 1,
        'Calculus': 1,
        'Chemistry': 1,
        'BEE': 1,
      },


      // Add more students as needed
    ];
  }
}
